### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by SupinePandora43** [SimplyProgger/SimplyProgger.github.io#1]
только если репа будет называться `SimplyProgger.github.io` ты сможешь сделать это своей главной страницей в `github-pages`

**Comment by SimplyProgger** [comment]
I tried, it didn't work

**Comment by SimplyProgger** [comment]
Github pages do not support node jsGithub pages do not support node js

**Comment by SupinePandora43** [comment]
you can use `webpack build`

**Comment by SimplyProgger** [comment]
How i make it?

**Comment by SupinePandora43** [comment]
@SimplyProgger that's only if you use webpack for plugins etc

**Comment by SupinePandora43** [comment]
https://github.com/SupinePandora43/SupinePandora43.github.io uses routes, you can see it here https://supinepandora43.github.io/ but using routes here isn't allowed, because github uses them to get your project's github pages like https://supinepandora43.github.io/ for supinepandora43.github.io repo, https://supinepandora43.github.io/electron-app for electron-app repo

**Comment by SimplyProgger** [comment]
The problem is that I do not have an index.html as such

**Comment by SimplyProgger** [comment]
I would prefer using heroku
